package oauthServer.exception;

public enum ErrorType {
	INVALID_REQUEST,
	UNAUTHORIZED_CLIENT,
	ACCESS_DENIED,
	UNSUPPORTED_RESPONSE_TYPE,
	INVALID_SCOPE,
	SERVER_ERROR,
	TEMPORARILLY_UNAVAILABLE	
}
